#include "kernels/01_naive.cu"
#include "kernels/02_smem_block.cu"
#include "kernels/03_block_tiling_1d.cu"
#include "kernels/04_block_tiling_2d.cu"
#include "kernels/05_block_tiling_2d_vec.cu"
#include "kernels/06_warp_tiling.cu"
